### ISSUE TITLE
An Question For Code

### ISSUE THREAD

**Issue by wanan12138** [1dNDN/RustedWarfareClient#2]
hello! 1dNDN I read your code then I have some question.
I can't understand this.
<img width="283" alt="s" src="https://user-images.githubusercontent.com/89179905/176626135-635e68cf-e7af-43d8-b911-af070549591b.png">
how can i understand this?
thanks for you! hava a good time

**Comment by 1dNDN** [comment]
The first eight bytes of a data packet contain the size of that packet and its type, which is indicated by a number. This is a list with all package types
